/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Centralized constants for cache names, app metadata, and URLs
const APP_NAME = 'SmartLab LIMS';
const SERVICE_WORKER_VERSION = '1.0.0';
const OFFLINE_FALLBACK_URL = '/offline.html';

const CACHE_NAMES = {
  PAGES: 'pages-cache',
  ASSETS: 'assets-cache',
  IMAGES: 'images-cache',
  API: 'api-cache',
  OFFLINE: 'offline-cache',
  APP: 'smartlab-v1',
} as const;

const NOTIFICATION_ICON_192 = '/icons/icon-192x192.png';
const NOTIFICATION_BADGE_72 = '/icons/badge-72x72.png';
const DEFAULT_VIBRATE_PATTERN: number[] = [100, 50, 100];

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Cache page navigations (html) with a Network First strategy
registerRoute(
  // Check to see if the request is a navigation to a new page
  ({ request }) => request.mode === 'navigate',
  // Use a Network First caching strategy
  new NetworkFirst({
    // Use a custom cache name
    cacheName: CACHE_NAMES.PAGES,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache CSS, JS, and Web Worker files with a Stale While Revalidate strategy
registerRoute(
  // Check to see if the request's destination is style for stylesheets, script for JavaScript, or worker for web worker
  ({ request }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'worker',
  // Use a Stale While Revalidate caching strategy
  new StaleWhileRevalidate({
    // Use a custom cache name
    cacheName: CACHE_NAMES.ASSETS,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache images with a Cache First strategy
registerRoute(
  // Check to see if the request's destination is style for an image
  ({ request }) => request.destination === 'image',
  // Use a Cache First caching strategy
  new CacheFirst({
    // Use a custom cache name
    cacheName: CACHE_NAMES.IMAGES,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache API responses with a Network First strategy
registerRoute(
  // Check to see if the request is for a Firebase API
  ({ url }) => url.origin === 'https://firestore.googleapis.com' ||
               url.origin === 'https://identitytoolkit.googleapis.com' ||
               url.origin === 'https://securetoken.googleapis.com',
  // Use a Network First caching strategy
  new NetworkFirst({
    // Use a custom cache name
    cacheName: CACHE_NAMES.API,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// Handle offline fallback
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst({
    cacheName: CACHE_NAMES.OFFLINE,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
    // Use a custom handler for offline fallback
    fallback: async () => {
      return caches.match(OFFLINE_FALLBACK_URL) || new Response('Offline', { status: 503 });
    },
  })
);

// Background sync for offline actions
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'background-sync') {
    event.waitUntil(doBackgroundSync());
  }
});

async function doBackgroundSync() {
  try {
    // Get all pending requests from IndexedDB
    const pendingRequests = await getPendingRequests();
    
    for (const request of pendingRequests as any[]) {
      try {
        // Attempt to send the request
        const response = await fetch((request as any).url, {
          method: (request as any).method,
          headers: (request as any).headers,
          body: (request as any).body,
        });
        
        if (response.ok) {
          // Remove from pending requests if successful
          await removePendingRequest((request as any).id);
        }
      } catch (error) {
        console.error('Background sync failed for request:', request, error);
      }
    }
  } catch (error) {
    console.error('Background sync error:', error);
  }
}

// Push notification handling
self.addEventListener('push', (event) => {
  const options = {
    body: event.data?.text() || 'New notification from SmartLab',
    icon: NOTIFICATION_ICON_192,
    badge: NOTIFICATION_BADGE_72,
    vibrate: DEFAULT_VIBRATE_PATTERN,
    data: {
      dateOfArrival: Date.now(),
      primaryKey: 1,
    },
    actions: [
      {
        action: 'explore',
        title: 'View',
        icon: '/icons/checkmark.png',
      },
      {
        action: 'close',
        title: 'Close',
        icon: '/icons/xmark.png',
      },
    ],
  };

  event.waitUntil(
    self.registration.showNotification(APP_NAME, options)
  );
});

// Notification click handling
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'explore') {
    // Open the app
    event.waitUntil(
      clients.openWindow('/')
    );
  }
});

// Install event - cache essential resources
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAMES.APP).then((cache) => {
      return cache.addAll([
        '/',
        OFFLINE_FALLBACK_URL,
        '/manifest.json',
        // Add other essential resources
      ]);
    })
  );
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAMES.APP) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});

// Helper functions for background sync
async function getPendingRequests() {
  // This would typically use IndexedDB
  // For now, return empty array
  return [];
}

async function removePendingRequest(_id: string) {
  // This would typically use IndexedDB
  // For now, do nothing
}

// Message handling for communication with main thread
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  
  if (event.data && event.data.type === 'GET_VERSION') {
    event.ports[0].postMessage({ version: SERVICE_WORKER_VERSION });
  }
}); 